# Use raushan/meraushan user/password credentials
version: '3.1'
services:
  rgqlcondb:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: raushan
      POSTGRES_PASSWORD: meraushan
    ports: 
        - 5431:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080